sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - docker volume ls
  - docker images
  - docker ps
  - docker-compose down --rmi all -v
